INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('Southeast Leisure Reps, Inc', '4-ALL-YOUR-POOL', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')
INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('Allen Pools', 'ALLENPOOLS', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')
INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('Alpine Pools', 'ALPINEPOOLS', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')
INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('Backyard Leisure', 'BACKYARDLEISURE', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')
INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('B&B Pools LLC', 'BANDBPOOLS', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')
INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('Burnett Pools, Inc.', 'BURNETTPOOLS', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')
INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('Central Iowa Pool & Spa', 'CENTRALIOWA', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')
INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('Clearwater Pool & Spa of Keene, Inc.', 'CLEARWATER', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')
INSERT INTO DEALERS (DEALER_NAME, DEALER_CODE, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE) VALUES ('Complete Pool & Spa Care', 'COMPLETEPOOL', '6095551234', 'example@me.com', 'Street Name', 'City Name,', 'State Name', '08215')

INSERT INTO APP_USERS (EMAIL, PASSWORD, ROLE, DEALER_REP_ID) VALUES ('admin@email.com', 'password', 'ADMIN', 1)
INSERT INTO APP_USERS (EMAIL, PASSWORD, ROLE, DEALER_REP_ID) VALUES ('test@user.com', 'secure', 'USER', 2)
INSERT INTO APP_USERS (EMAIL, PASSWORD, ROLE, DEALER_REP_ID) VALUES ('krstice@gmail.com', 'password', 'USER', 3)

INSERT INTO QUOTE (ORDER_NUMBER, REQUEST_DATE, QUOTE_DEALER_ID) VALUES(1000, 'REQ DATE', 1)

INSERT INTO CUSTOMER (FIRST_NAME, LAST_NAME, PHONE_NUMBER, EMAIL, STREET_NAME, CITY_NAME, STATE_NAME, ZIP_CODE, QUOTE_ID) VALUES ('Kev', 'Wags', '6095551234', 'example@me.com', 'Street Name', 'City Name', 'State Name', '08215', 1)

--INSERT INTO POOL_SIZES (DEPTH, LENGTH, WIDTH) VALUES (8, 60, 40)
--INSERT INTO POOL_SIZES (DEPTH, LENGTH, WIDTH) VALUES (8, 42, 20)
--INSERT INTO POOL_SIZES (DEPTH, LENGTH, WIDTH) VALUES (6, 28, 16)

--INSERT INTO POOLS (POOL_TYPE, POOL_CODE, POOL_METRIC, METRIC_CODE, SIZE_ID) VALUES ('EMERALD', 'EM', 'METRIC EMERALD', 'METEM', 1)
--INSERT INTO POOLS (POOL_TYPE, POOL_CODE, POOL_METRIC, METRIC_CODE, SIZE_ID) VALUES ('EMERALD', 'EM', 'METRIC EMERALD', 'METEM', 2)
--INSERT INTO POOLS (POOL_TYPE, POOL_CODE, POOL_METRIC, METRIC_CODE, SIZE_ID) VALUES ('BLUE LAGOON', 'BL', 'METRIC BLUI LAGOON', 'METBL', 3)



