INSERT INTO APP_USERS (EMAIL, PASSWORD, ROLE) VALUES ('admin@email.com', 'password', 'ADMIN')
INSERT INTO APP_USERS (EMAIL, PASSWORD, ROLE) VALUES ('test@user.com', 'secure', 'USER')
INSERT INTO APP-USERS (EMAIL, PASSWORD, ROLE) VALUE ('krstice@gmail.com', 'password', 'USER')

INSERT INTO POOL_SIZES (DEPTH, LENGTH, WIDTH) VALUES (8, 60, 40)
INSERT INTO POOL_SIZES (DEPTH, LENGTH, WIDTH) VALUES (8, 42, 20)
INSERT INTO POOL_SIZES (DEPTH, LENGTH, WIDTH) VALUES (6, 28, 16)

INSERT INTO POOLS (POOL_TYPE, POOL_CODE, POOL_METRIC, METRIC_CODE, SIZE_ID) VALUES ('EMERALD', 'EM', 'METRIC EMERALD', 'METEM', 1)
INSERT INTO POOLS (POOL_TYPE, POOL_CODE, POOL_METRIC, METRIC_CODE, SIZE_ID) VALUES ('EMERALD', 'EM', 'METRIC EMERALD', 'METEM', 2)
INSERT INTO POOLS (POOL_TYPE, POOL_CODE, POOL_METRIC, METRIC_CODE, SIZE_ID) VALUES ('BLUE LAGOON', 'BL', 'METRIC BLUI LAGOON', 'METBL', 3)